Adding vendor folder to allow Prow setup to finalize
Prow was returning this error when trying to setup this repository.

```
/go/src/github.com/netobserv/network-observability-operator/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
Error: err: exit status 1: stderr: go: inconsistent vendoring in /go/src/github.com/netobserv/network-observability-operator:
	github.com/onsi/ginkgo@v1.16.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/onsi/gomega@v1.13.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/stretchr/testify@v1.7.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/apimachinery@v0.21.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/client-go@v0.21.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	sigs.k8s.io/controller-runtime@v0.9.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```